// <auto-generated />
using System;
using API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(_4vodsContext))]
    [Migration("20250501132730_cursoEscolar")]
    partial class cursoEscolar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("API.Models.asignatura", b =>
                {
                    b.Property<int>("ID_ASIGNATURA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_ASIGNATURA"));

                    b.Property<int?>("ID_CURSO")
                        .HasColumnType("int(11)");

                    b.Property<string>("NOMBRE")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ID_ASIGNATURA")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ID_CURSO" }, "ID_CURSO");

                    b.ToTable("asignatura", (string)null);
                });

            modelBuilder.Entity("API.Models.curso", b =>
                {
                    b.Property<int>("ID_CURSO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_CURSO"));

                    b.Property<string>("NOMBRE")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ID_CURSO")
                        .HasName("PRIMARY");

                    b.ToTable("curso", (string)null);
                });

            modelBuilder.Entity("API.Models.cursoEscolar", b =>
                {
                    b.Property<int>("ID_CURSOESCOLAR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_CURSOESCOLAR"));

                    b.Property<string>("DESCRIPCION")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ID_CURSOESCOLAR")
                        .HasName("PRIMARY");

                    b.ToTable("cursoEscolar", (string)null);
                });

            modelBuilder.Entity("API.Models.difusion", b =>
                {
                    b.Property<int>("ID_DIFUSION")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_DIFUSION"));

                    b.Property<int>("ID_INICIATIVA")
                        .HasColumnType("int(11)");

                    b.Property<string>("LINK")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID_DIFUSION")
                        .HasName("PRIMARY");

                    b.HasIndex("ID_INICIATIVA");

                    b.ToTable("difusion", (string)null);
                });

            modelBuilder.Entity("API.Models.entidad", b =>
                {
                    b.Property<int>("ID_ENTIDAD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_ENTIDAD"));

                    b.Property<string>("DESCRIPCION")
                        .HasColumnType("text");

                    b.Property<string>("NOMBRE")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ID_ENTIDAD")
                        .HasName("PRIMARY");

                    b.ToTable("entidad", (string)null);
                });

            modelBuilder.Entity("API.Models.iniciativa", b =>
                {
                    b.Property<int>("ID_INICIATIVA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_INICIATIVA"));

                    b.Property<string>("DESCRIPCION")
                        .HasColumnType("text");

                    b.Property<string>("FECHA_FIN")
                        .HasColumnType("longtext");

                    b.Property<string>("FECHA_INICIO")
                        .HasColumnType("longtext");

                    b.Property<int?>("HORAS")
                        .HasColumnType("int(11)");

                    b.Property<int?>("ID_CURSOESCOLAR")
                        .HasColumnType("int(11)");

                    b.Property<bool>("NUEVA")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PRODUCTO_FINAL")
                        .HasColumnType("text");

                    b.Property<string>("TIPO")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TITULO")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ID_INICIATIVA")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ID_CURSOESCOLAR" }, "ID_CURSOESCOLAR");

                    b.ToTable("iniciativas");
                });

            modelBuilder.Entity("API.Models.meta", b =>
                {
                    b.Property<int>("ID_META")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_META"));

                    b.Property<string>("DESCRIPCION")
                        .HasColumnType("text");

                    b.Property<int?>("ID_ODS")
                        .HasColumnType("int(11)");

                    b.HasKey("ID_META")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ID_ODS" }, "ID_ODS");

                    b.ToTable("metas");
                });

            modelBuilder.Entity("API.Models.od", b =>
                {
                    b.Property<int>("ID_ODS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_ODS"));

                    b.Property<string>("DESCRIPCION")
                        .HasColumnType("text");

                    b.Property<string>("DIMENSION")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NOMBRE")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ID_ODS")
                        .HasName("PRIMARY");

                    b.ToTable("ods");
                });

            modelBuilder.Entity("API.Models.profesore", b =>
                {
                    b.Property<int>("ID_PROFESOR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_PROFESOR"));

                    b.Property<string>("APELLIDO1")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("APELLIDO2")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly?>("FECHA_NACIMIENTO")
                        .HasColumnType("date");

                    b.Property<string>("NOMBRE")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ID_PROFESOR")
                        .HasName("PRIMARY");

                    b.ToTable("profesores");
                });

            modelBuilder.Entity("asignaturas_iniciativa", b =>
                {
                    b.Property<int>("ID_ASIGNATURA")
                        .HasColumnType("int(11)");

                    b.Property<int>("ID_INICIATIVA")
                        .HasColumnType("int(11)");

                    b.HasKey("ID_ASIGNATURA", "ID_INICIATIVA")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "ID_INICIATIVA" }, "ID_INICIATIVA");

                    b.ToTable("asignaturas_iniciativa", (string)null);
                });

            modelBuilder.Entity("entidad_iniciativa", b =>
                {
                    b.Property<int>("ID_ENTIDAD")
                        .HasColumnType("int(11)");

                    b.Property<int>("ID_INICIATIVA")
                        .HasColumnType("int(11)");

                    b.HasKey("ID_ENTIDAD", "ID_INICIATIVA")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "ID_INICIATIVA" }, "ID_INICIATIVA")
                        .HasDatabaseName("ID_INICIATIVA1");

                    b.ToTable("entidad_iniciativa", (string)null);
                });

            modelBuilder.Entity("metas_iniciativa", b =>
                {
                    b.Property<int>("ID_INICIATIVA")
                        .HasColumnType("int(11)");

                    b.Property<int>("ID_META")
                        .HasColumnType("int(11)");

                    b.HasKey("ID_INICIATIVA", "ID_META")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "ID_META" }, "ID_META");

                    b.ToTable("metas_iniciativa", (string)null);
                });

            modelBuilder.Entity("profesores_iniciativa", b =>
                {
                    b.Property<int>("ID_PROFESOR")
                        .HasColumnType("int(11)");

                    b.Property<int>("ID_INICIATIVA")
                        .HasColumnType("int(11)");

                    b.HasKey("ID_PROFESOR", "ID_INICIATIVA")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "ID_INICIATIVA" }, "ID_INICIATIVA")
                        .HasDatabaseName("ID_INICIATIVA2");

                    b.ToTable("profesores_iniciativa", (string)null);
                });

            modelBuilder.Entity("API.Models.asignatura", b =>
                {
                    b.HasOne("API.Models.curso", "ID_CURSONavigation")
                        .WithMany("asignaturas")
                        .HasForeignKey("ID_CURSO")
                        .HasConstraintName("asignatura_ibfk_1");

                    b.Navigation("ID_CURSONavigation");
                });

            modelBuilder.Entity("API.Models.difusion", b =>
                {
                    b.HasOne("API.Models.iniciativa", null)
                        .WithMany("difusiones")
                        .HasForeignKey("ID_INICIATIVA")
                        .IsRequired()
                        .HasConstraintName("difusion_ibfk_1");
                });

            modelBuilder.Entity("API.Models.iniciativa", b =>
                {
                    b.HasOne("API.Models.cursoEscolar", "ID_CURSOESCOLARNavigation")
                        .WithMany("iniciativas")
                        .HasForeignKey("ID_CURSOESCOLAR")
                        .HasConstraintName("iniciativa_ibfk_cursoEscolar");

                    b.Navigation("ID_CURSOESCOLARNavigation");
                });

            modelBuilder.Entity("API.Models.meta", b =>
                {
                    b.HasOne("API.Models.od", "ID_ODSNavigation")
                        .WithMany("meta")
                        .HasForeignKey("ID_ODS")
                        .HasConstraintName("metas_ibfk_1");

                    b.Navigation("ID_ODSNavigation");
                });

            modelBuilder.Entity("asignaturas_iniciativa", b =>
                {
                    b.HasOne("API.Models.asignatura", null)
                        .WithMany()
                        .HasForeignKey("ID_ASIGNATURA")
                        .IsRequired()
                        .HasConstraintName("asignaturas_iniciativa_ibfk_1");

                    b.HasOne("API.Models.iniciativa", null)
                        .WithMany()
                        .HasForeignKey("ID_INICIATIVA")
                        .IsRequired()
                        .HasConstraintName("asignaturas_iniciativa_ibfk_2");
                });

            modelBuilder.Entity("entidad_iniciativa", b =>
                {
                    b.HasOne("API.Models.entidad", null)
                        .WithMany()
                        .HasForeignKey("ID_ENTIDAD")
                        .IsRequired()
                        .HasConstraintName("entidad_iniciativa_ibfk_1");

                    b.HasOne("API.Models.iniciativa", null)
                        .WithMany()
                        .HasForeignKey("ID_INICIATIVA")
                        .IsRequired()
                        .HasConstraintName("entidad_iniciativa_ibfk_2");
                });

            modelBuilder.Entity("metas_iniciativa", b =>
                {
                    b.HasOne("API.Models.iniciativa", null)
                        .WithMany()
                        .HasForeignKey("ID_INICIATIVA")
                        .IsRequired()
                        .HasConstraintName("metas_iniciativa_ibfk_1");

                    b.HasOne("API.Models.meta", null)
                        .WithMany()
                        .HasForeignKey("ID_META")
                        .IsRequired()
                        .HasConstraintName("metas_iniciativa_ibfk_2");
                });

            modelBuilder.Entity("profesores_iniciativa", b =>
                {
                    b.HasOne("API.Models.iniciativa", null)
                        .WithMany()
                        .HasForeignKey("ID_INICIATIVA")
                        .IsRequired()
                        .HasConstraintName("profesores_iniciativa_ibfk_2");

                    b.HasOne("API.Models.profesore", null)
                        .WithMany()
                        .HasForeignKey("ID_PROFESOR")
                        .IsRequired()
                        .HasConstraintName("profesores_iniciativa_ibfk_1");
                });

            modelBuilder.Entity("API.Models.curso", b =>
                {
                    b.Navigation("asignaturas");
                });

            modelBuilder.Entity("API.Models.cursoEscolar", b =>
                {
                    b.Navigation("iniciativas");
                });

            modelBuilder.Entity("API.Models.iniciativa", b =>
                {
                    b.Navigation("difusiones");
                });

            modelBuilder.Entity("API.Models.od", b =>
                {
                    b.Navigation("meta");
                });
#pragma warning restore 612, 618
        }
    }
}
