-- Crear la base de datos
CREATE DATABASE _4vODS;
USE _4vODS;

-- Tabla ODS
CREATE TABLE ODS (
    ID_ODS INT PRIMARY KEY,
    NOMBRE VARCHAR(255),
    DESCRIPCION TEXT,
    DIMENSION VARCHAR(50) CHECK (DIMENSION IN ('Social', 'Económica', 'Medioambiental'))
);

-- Tabla METAS
CREATE TABLE METAS (
    ID_META INT PRIMARY KEY,
    ID_ODS INT,
    DESCRIPCION TEXT,
    FOREIGN KEY (ID_ODS) REFERENCES ODS(ID_ODS)
);

-- Tabla INICIATIVAS
CREATE TABLE INICIATIVAS (
    ID_INICIATIVA INT PRIMARY KEY,
    TITULO VARCHAR(255),
    HORAS INT,
    FECHA_INICIO varchar(10),
    FECHA_FIN varchar(10),
    DESCRIPCION TEXT,
    TIPO VARCHAR(50) CHECK (TIPO IN ('Proyecto', 'Charla', 'Taller')),
    PRODUCTO_FINAL TEXT,
    NUEVA BOOLEAN,
    DIFUSION TEXT
);

-- Tabla METAS_INICIATIVA
CREATE TABLE METAS_INICIATIVA (
    ID_INICIATIVA INT,
    ID_META INT,
    PRIMARY KEY (ID_INICIATIVA, ID_META),
    FOREIGN KEY (ID_INICIATIVA) REFERENCES INICIATIVAS(ID_INICIATIVA),
    FOREIGN KEY (ID_META) REFERENCES METAS(ID_META)
);

-- Tabla PROFESORES
CREATE TABLE PROFESORES (
    ID_PROFESOR INT PRIMARY KEY,
    NOMBRE VARCHAR(255),
    APELLIDO1 VARCHAR(255),
    APELLIDO2 VARCHAR(255),
    FECHA_NACIMIENTO DATE
);

-- Tabla PROFESORES_INICIATIVA
CREATE TABLE PROFESORES_INICIATIVA (
    ID_PROFESOR INT,
    ID_INICIATIVA INT,
    PRIMARY KEY (ID_PROFESOR, ID_INICIATIVA),
    FOREIGN KEY (ID_PROFESOR) REFERENCES PROFESORES(ID_PROFESOR),
    FOREIGN KEY (ID_INICIATIVA) REFERENCES INICIATIVAS(ID_INICIATIVA)
);

-- Tabla ENTIDAD
CREATE TABLE ENTIDAD (
    ID_ENTIDAD INT PRIMARY KEY,
    NOMBRE VARCHAR(255),
    DESCRIPCION TEXT
);

-- Tabla ENTIDAD_INICIATIVA
CREATE TABLE ENTIDAD_INICIATIVA (
    ID_ENTIDAD INT,
    ID_INICIATIVA INT,
    PRIMARY KEY (ID_ENTIDAD, ID_INICIATIVA),
    FOREIGN KEY (ID_ENTIDAD) REFERENCES ENTIDAD(ID_ENTIDAD),
    FOREIGN KEY (ID_INICIATIVA) REFERENCES INICIATIVAS(ID_INICIATIVA)
);

-- Tabla CURSO
CREATE TABLE CURSO (
    ID_CURSO INT PRIMARY KEY,
    NOMBRE VARCHAR(255)
);

-- Tabla ASIGNATURA
CREATE TABLE ASIGNATURA (
    ID_ASIGNATURA INT PRIMARY KEY,
    ID_CURSO INT,
    NOMBRE VARCHAR(255),
    FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO)
);

-- Tabla ASIGNATURAS_INICIATIVA
CREATE TABLE ASIGNATURAS_INICIATIVA (
    ID_ASIGNATURA INT,
    ID_INICIATIVA INT,
    PRIMARY KEY (ID_ASIGNATURA, ID_INICIATIVA),
    FOREIGN KEY (ID_ASIGNATURA) REFERENCES ASIGNATURA(ID_ASIGNATURA),
    FOREIGN KEY (ID_INICIATIVA) REFERENCES INICIATIVAS(ID_INICIATIVA)
);