-- Verificar si la base de datos existe antes de crearla
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'IniciativasDB')
    CREATE DATABASE IniciativasDB;
GO

USE IniciativasDB;
GO

CREATE TABLE ODS (
    NUMERO_ODS INT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    DESCRIPCION TEXT
);

CREATE TABLE METAS (
    NUMERO_ODS INT,
    CARACTER_META VARCHAR(255),
    DESCRIPCION TEXT,
    PRIMARY KEY (NUMERO_ODS, CARACTER_META),
    FOREIGN KEY (NUMERO_ODS) REFERENCES ODS(NUMERO_ODS)
);

CREATE TABLE INICIATIVAS (
    COD_INICIATIVA INT IDENTITY(1,1) PRIMARY KEY,
    HORAS INT NOT NULL,
    TITULO VARCHAR(255) NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL
);

CREATE TABLE METAS_INICIATIVA (
    NUMERO_ODS INT,
    CARACTER_META VARCHAR(255),
    COD_INICIATIVA INT,
    PRIMARY KEY (NUMERO_ODS, CARACTER_META, COD_INICIATIVA),
    FOREIGN KEY (NUMERO_ODS, CARACTER_META) REFERENCES METAS(NUMERO_ODS, CARACTER_META),
    FOREIGN KEY (COD_INICIATIVA) REFERENCES INICIATIVAS(COD_INICIATIVA)
);

CREATE TABLE CONTRATANTE (
    COD_CONTRATANTE INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE_CONTRATANTE VARCHAR(255) NOT NULL,
    DESCRIPCION TEXT
);

CREATE TABLE CONTRATANTE_INICIATIVA (
    COD_CONTRATANTE INT,
    COD_INICIATIVA INT,
    PRIMARY KEY (COD_CONTRATANTE, COD_INICIATIVA),
    FOREIGN KEY (COD_CONTRATANTE) REFERENCES CONTRATANTE(COD_CONTRATANTE),
    FOREIGN KEY (COD_INICIATIVA) REFERENCES INICIATIVAS(COD_INICIATIVA)
);

CREATE TABLE PROFESORES (
    ID_PROFESOR INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE_PROFESOR VARCHAR(255) NOT NULL,
    APELLIDO1 VARCHAR(255) NOT NULL,
    APELLIDO2 VARCHAR(255) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL
);

CREATE TABLE PROFESORES_INICIATIVA (
    ID_PROFESOR INT,
    COD_INICIATIVA INT,
    PRIMARY KEY (ID_PROFESOR, COD_INICIATIVA),
    FOREIGN KEY (ID_PROFESOR) REFERENCES PROFESORES(ID_PROFESOR),
    FOREIGN KEY (COD_INICIATIVA) REFERENCES INICIATIVAS(COD_INICIATIVA)
);

CREATE TABLE CURSO (
    NOMBRE_CURSO VARCHAR(255) PRIMARY KEY
);

CREATE TABLE ASIGNATURA (
    COD_ASIGNATURA INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE_CURSO VARCHAR(255),
    NOMBRE_ASIGNATURA VARCHAR(255) NOT NULL,
    FOREIGN KEY (NOMBRE_CURSO) REFERENCES CURSO(NOMBRE_CURSO)
);

CREATE TABLE ASIGNATURAS_INICIATIVA (
    COD_ASIGNATURA INT,
    COD_INICIATIVA INT,
    PRIMARY KEY (COD_ASIGNATURA, COD_INICIATIVA),
    FOREIGN KEY (COD_ASIGNATURA) REFERENCES ASIGNATURA(COD_ASIGNATURA),
    FOREIGN KEY (COD_INICIATIVA) REFERENCES INICIATIVAS(COD_INICIATIVA)
);
